### ISSUE TITLE
Upgrade gtk to 0.18

### ISSUE THREAD

**Issue by ansirotenko** [uriegel/systemicons#5]
System icons has dependency to old version of 'gtk' library. It becomes very unfortunate when you want to use systemicons to build [Tauri ](https://tauri.app/) projects. [Here](https://github.com/tauri-apps/tauri/discussions/8563) is issue on Tauri tracker related to systemicons.

Could you please upgrade version of gtk at your dependencies from 0.14 to 0.18. That would open a lot of possibilities for innovators.

**Comment by intoop** [comment]
> System icons has dependency to old version of 'gtk' library. It becomes very unfortunate when you want to use systemicons to build [Tauri ](https://tauri.app/) projects. [Here](https://github.com/tauri-apps/tauri/discussions/8563) is issue on Tauri tracker related to systemicons.
> 
> Could you please upgrade version of gtk at your dependencies from 0.14 to 0.18. That would open a lot of possibilities for innovators.

You can try me fork: https://github.com/u3l6/systemicons

**Comment by uriegel** [comment]
The crate is updated to use GTK3 version 0.18. In near future "systemicons" will be updated to use GTK4

**Comment by ansirotenko** [comment]
> The crate is updated to use GTK3 version 0.18. In near future "systemicons" will be updated to use GTK4

Thanks a lot. Just applied it to my application. https://github.com/ansirotenko/ccv
